apiVersion: harness.io/v1
kind: Component
type: service
identifier: teamk_kroger455ip11
name: teamk_kroger455ip11
owner: group:account/Kroger
orgIdentifier: kroger455org
projectIdentifier: kroger455ip11
spec:
  lifecycle: experimental
metadata:
  description: test_kroger455ip11
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/harnessworkshop/teamk_kroger455ip11/blob/main
    backstage.io/source-location: url:https://github.com/harnessworkshop/teamk_kroger455ip11
  links:
  - title: Website
    url: https://harness.io
  tags:
  - my-sample
